run:
  deadline: 5m
  skip-dirs:
    - imgui
    - wrapper

linters:
  enable-all: true

  # linters are disabled if their majority of issues is considered false-positive (intended code)
  # and the remaining issues (if existing) aren't worth it.
  disable:
    - gochecknoglobals
    - goimports # disabled because of so many false-positives with "imgui-go"
    - gofumpt # disabled because no extra need
    - wsl # this one has become too pedantic
    - ifshort # was not available in v.1.28.3 and will be skipped for now
    - exhaustivestruct # was not available in v.1.28.3 and will be skipped for now
    - nlreturn # was not available in v.1.28.3 and will be skipped for now
    - paralleltest # was not available in v.1.28.3 and will be skipped for now
    - varnamelen # was not available in v.1.28.3 and will be skipped for now
    - gci # was not available in v.1.28.3 and will be skipped for now
    - forcetypeassert # was not available in v.1.28.3 and will be skipped for now
    - gomnd # was not available in v.1.28.3 and will be skipped for now

issues:
  exclude-use-default: false # disable filtering of defaults for better zero-issue policy
  exclude:
    # There is a lot of pointer-mangling happening here, so disable this govet warning
    - possible misuse of unsafe.Pointer
  max-per-linter: 0 # disable limit; report all issues of a linter
  max-same-issues: 0 # disable limit; report all issues of the same issue

linters-settings:
  lll:
    line-length: 160
  gocritic:
    disabled-checks:
      - dupSubExpr
      - commentFormatting
      - deprecatedComment
